table 'public frequencyagegroupemployees'
	lineageTag: 908145cc-4189-4f9a-953b-f3d3bb65dbc6

	column agegroup
		dataType: string
		lineageTag: f34855fe-9d3f-45cc-baaf-9639ea8a99d1
		summarizeBy: none
		sourceColumn: agegroup
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column countofemployees
		dataType: int64
		formatString: 0
		lineageTag: 731804a3-8f4e-45a8-850d-4b838f1a521e
		summarizeBy: sum
		sourceColumn: countofemployees

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 9ddd941b-fd42-4731-8984-d706655b6c1e
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition 'public frequencyagegroupemployees' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost", "Frequency"),
				    public_frequencyagegroupemployees = Source{[Schema="public",Item="frequencyagegroupemployees"]}[Data],
				    #"Added Index" = Table.AddIndexColumn(public_frequencyagegroupemployees, "Index", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

