table DummyVariables
	lineageTag: 8f0cd95d-59c5-43bf-b094-f07b6d1de45a

	column Gender
		dataType: int64
		formatString: 0
		lineageTag: 4292855b-3348-4695-8277-30373f2b88d0
		summarizeBy: sum
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Married
		dataType: int64
		formatString: 0
		lineageTag: e353694e-aa2b-47ea-97a7-7af012bf7e5e
		summarizeBy: sum
		sourceColumn: Married

		annotation SummarizationSetBy = Automatic

	column Dependents
		dataType: int64
		formatString: 0
		lineageTag: 937b7239-8ca4-413c-9360-bfa5b9a475a0
		summarizeBy: sum
		sourceColumn: Dependents

		annotation SummarizationSetBy = Automatic

	column Education
		dataType: int64
		formatString: 0
		lineageTag: 1d330ada-608a-4859-8e71-6c631935c1e6
		summarizeBy: sum
		sourceColumn: Education

		annotation SummarizationSetBy = Automatic

	column Self_Employed
		dataType: int64
		formatString: 0
		lineageTag: 7f1deef9-abb7-40c4-8c1b-af47c5bd5645
		summarizeBy: sum
		sourceColumn: Self_Employed

		annotation SummarizationSetBy = Automatic

	column ApplicantIncome
		dataType: double
		lineageTag: c241f08e-3e5d-469e-a1ed-d0b0d1418367
		summarizeBy: sum
		sourceColumn: ApplicantIncome

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CoapplicantIncome
		dataType: double
		lineageTag: 2bb316f2-1d46-4349-b8dc-c4825610927e
		summarizeBy: sum
		sourceColumn: CoapplicantIncome

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LoanAmount
		dataType: double
		lineageTag: 199c8e19-1e01-4274-9c34-9c287dddc53f
		summarizeBy: sum
		sourceColumn: LoanAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Loan_Amount_Term
		dataType: double
		lineageTag: 5d5fe953-bb23-4544-855b-93162d4e637d
		summarizeBy: sum
		sourceColumn: Loan_Amount_Term

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Credit_History
		dataType: int64
		formatString: 0
		lineageTag: caac5419-33a6-43ec-a80c-a3f016fea114
		summarizeBy: sum
		sourceColumn: Credit_History

		annotation SummarizationSetBy = Automatic

	column Property_Area
		dataType: int64
		formatString: 0
		lineageTag: 1a13e17f-ae73-4322-b25d-90c288cadfa1
		summarizeBy: sum
		sourceColumn: Property_Area

		annotation SummarizationSetBy = Automatic

	column Loan_Status
		dataType: int64
		formatString: 0
		lineageTag: 14c52377-438d-4304-9d74-dc6f252930e6
		summarizeBy: sum
		sourceColumn: Loan_Status

		annotation SummarizationSetBy = Automatic

	partition DummyVariables = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("E:\Data Analyst Projects\Loan Status Prediction\Collected Datasets\Exported Dummysets Of Loan Prediction.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Gender", Int64.Type}, {"Married", Int64.Type}, {"Dependents", Int64.Type}, {"Education", Int64.Type}, {"Self_Employed", Int64.Type}, {"ApplicantIncome", type number}, {"CoapplicantIncome", type number}, {"LoanAmount", type number}, {"Loan_Amount_Term", type number}, {"Credit_History", Int64.Type}, {"Property_Area", Int64.Type}, {"Loa0_Status", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Loa0_Status", "Loan_Status"}})
				in
				    #"Renamed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

